USE bookstore_db;

INSERT INTO Publisher (name) VALUES ('Robbins, Cannon and Molina');
INSERT INTO Publisher (name) VALUES ('Nelson, Graham and Maxwell');
INSERT INTO Publisher (name) VALUES ('Michael LLC');
INSERT INTO Publisher (name) VALUES ('Bernard LLC');
INSERT INTO Publisher (name) VALUES ('Lynch, Doyle and Smith');
INSERT INTO Publisher (name) VALUES ('Blankenship-Franco');
INSERT INTO Publisher (name) VALUES ('Gray-Hernandez');
INSERT INTO Publisher (name) VALUES ('Ball, Blankenship and Harris');
INSERT INTO Publisher (name) VALUES ('Warren, Gentry and Parker');
INSERT INTO Publisher (name) VALUES ('Russell, Lowery and Miller');
INSERT INTO book_language (language_name) VALUES ('English');
INSERT INTO book_language (language_name) VALUES ('French');
INSERT INTO book_language (language_name) VALUES ('German');
INSERT INTO book_language (language_name) VALUES ('Spanish');
INSERT INTO book_language (language_name) VALUES ('Chinese');
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Senior.', 'health', 10, 4, 77.59);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Test strategy.', 'strong', 10, 4, 41.52);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Step draw field address.', 'where', 2, 1, 31.57);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Partner member.', 'think', 3, 2, 65.72);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Whom attack amount.', 'interesting', 8, 5, 88.07);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Each here.', 'population', 5, 2, 79.55);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Admit test trip.', 'specific', 5, 2, 48.25);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('While my.', 'sell', 1, 5, 73.01);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Enter agent.', 'worker', 5, 2, 90.60);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Help tend task.', 'order', 7, 2, 91.50);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Value they.', 'rate', 6, 3, 11.62);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('A meeting black.', 'despite', 6, 3, 53.19);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Around goal city.', 'increase', 4, 4, 35.09);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Responsibility seat.', 'air', 7, 2, 59.75);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Enter population mission.', 'tonight', 8, 4, 93.66);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Write draw.', 'help', 10, 4, 10.97);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Good add four.', 'involve', 1, 3, 64.03);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Suggest road analysis least.', 'hard', 10, 4, 48.92);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Many bit same interest.', 'glass', 9, 3, 38.22);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Listen news.', 'with', 5, 1, 93.37);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Television indeed control parent.', 'operation', 8, 2, 30.20);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Building police these community.', 'Mrs', 5, 2, 85.92);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Thing play.', 'authority', 9, 2, 72.27);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Finish.', 'us', 5, 2, 98.53);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Million red.', 'father', 5, 1, 11.13);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Him prepare.', 'include', 4, 2, 62.19);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Allow computer drive.', 'ball', 5, 5, 79.38);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Anyone red.', 'all', 1, 4, 82.37);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Pretty pay.', 'real', 5, 4, 87.39);
INSERT INTO book (title, genre, publisher_id, language_id, price) VALUES ('Certain two look college.', 'experience', 6, 3, 75.15);
INSERT INTO author (first_name, last_name) VALUES ('Jason', 'Henderson');
INSERT INTO author (first_name, last_name) VALUES ('Donald', 'Carr');
INSERT INTO author (first_name, last_name) VALUES ('Robert', 'Morales');
INSERT INTO author (first_name, last_name) VALUES ('Brooke', 'Perez');
INSERT INTO author (first_name, last_name) VALUES ('Nathan', 'Morales');
INSERT INTO author (first_name, last_name) VALUES ('Erin', 'Valenzuela');
INSERT INTO author (first_name, last_name) VALUES ('Connie', 'Gray');
INSERT INTO author (first_name, last_name) VALUES ('Joy', 'Reed');
INSERT INTO author (first_name, last_name) VALUES ('Richard', 'Bond');
INSERT INTO author (first_name, last_name) VALUES ('Robert', 'Bennett');
INSERT INTO author (first_name, last_name) VALUES ('Anthony', 'Duncan');
INSERT INTO author (first_name, last_name) VALUES ('Danny', 'Wolfe');
INSERT INTO author (first_name, last_name) VALUES ('Barbara', 'Henderson');
INSERT INTO author (first_name, last_name) VALUES ('Julie', 'Williams');
INSERT INTO author (first_name, last_name) VALUES ('Elizabeth', 'Johnson');
INSERT INTO author (first_name, last_name) VALUES ('Arthur', 'Williams');
INSERT INTO author (first_name, last_name) VALUES ('Shannon', 'West');
INSERT INTO author (first_name, last_name) VALUES ('Brittany', 'Anthony');
INSERT INTO author (first_name, last_name) VALUES ('Mark', 'Mcbride');
INSERT INTO author (first_name, last_name) VALUES ('Patricia', 'Owen');
INSERT INTO book_author (book_id, author_id) VALUES (20, 3);
INSERT INTO book_author (book_id, author_id) VALUES (18, 4);
INSERT INTO book_author (book_id, author_id) VALUES (12, 1);
INSERT INTO book_author (book_id, author_id) VALUES (22, 15);
INSERT INTO book_author (book_id, author_id) VALUES (20, 1);
INSERT INTO book_author (book_id, author_id) VALUES (22, 6);
INSERT INTO book_author (book_id, author_id) VALUES (9, 1);
INSERT INTO book_author (book_id, author_id) VALUES (1, 7);
INSERT INTO book_author (book_id, author_id) VALUES (15, 3);
INSERT INTO book_author (book_id, author_id) VALUES (3, 18);
INSERT INTO book_author (book_id, author_id) VALUES (21, 3);
INSERT INTO book_author (book_id, author_id) VALUES (18, 11);
INSERT INTO book_author (book_id, author_id) VALUES (21, 10);
INSERT INTO book_author (book_id, author_id) VALUES (20, 13);
INSERT INTO book_author (book_id, author_id) VALUES (26, 9);
INSERT INTO book_author (book_id, author_id) VALUES (12, 4);
INSERT INTO book_author (book_id, author_id) VALUES (26, 9);
INSERT INTO book_author (book_id, author_id) VALUES (3, 19);
INSERT INTO book_author (book_id, author_id) VALUES (21, 17);
INSERT INTO book_author (book_id, author_id) VALUES (6, 14);
INSERT INTO book_author (book_id, author_id) VALUES (22, 16);
INSERT INTO book_author (book_id, author_id) VALUES (17, 1);
INSERT INTO book_author (book_id, author_id) VALUES (22, 3);
INSERT INTO book_author (book_id, author_id) VALUES (25, 9);
INSERT INTO book_author (book_id, author_id) VALUES (10, 13);
INSERT INTO book_author (book_id, author_id) VALUES (10, 12);
INSERT INTO book_author (book_id, author_id) VALUES (14, 3);
INSERT INTO book_author (book_id, author_id) VALUES (4, 6);
INSERT INTO book_author (book_id, author_id) VALUES (1, 10);
INSERT INTO book_author (book_id, author_id) VALUES (12, 17);
INSERT INTO book_author (book_id, author_id) VALUES (18, 11);
INSERT INTO book_author (book_id, author_id) VALUES (9, 18);
INSERT INTO book_author (book_id, author_id) VALUES (20, 9);
INSERT INTO book_author (book_id, author_id) VALUES (4, 16);
INSERT INTO book_author (book_id, author_id) VALUES (29, 4);
INSERT INTO book_author (book_id, author_id) VALUES (6, 8);
INSERT INTO book_author (book_id, author_id) VALUES (21, 8);
INSERT INTO book_author (book_id, author_id) VALUES (11, 5);
INSERT INTO book_author (book_id, author_id) VALUES (17, 4);
INSERT INTO book_author (book_id, author_id) VALUES (1, 7);
INSERT INTO book_author (book_id, author_id) VALUES (4, 18);
INSERT INTO book_author (book_id, author_id) VALUES (23, 20);
INSERT INTO book_author (book_id, author_id) VALUES (16, 18);
INSERT INTO book_author (book_id, author_id) VALUES (6, 20);
INSERT INTO book_author (book_id, author_id) VALUES (9, 9);
INSERT INTO book_author (book_id, author_id) VALUES (10, 1);
INSERT INTO book_author (book_id, author_id) VALUES (22, 14);
INSERT INTO book_author (book_id, author_id) VALUES (7, 1);
INSERT INTO book_author (book_id, author_id) VALUES (13, 8);
INSERT INTO book_author (book_id, author_id) VALUES (28, 17);
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('William', 'Hughes', 'kendra58@hotmail.com', '9467769070');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Kevin', 'Lloyd', 'yvelez@bullock.com', '925-084-1197');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Alec', 'Ballard', 'calebpatton@hotmail.com', '605-857-2073');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Kathryn', 'Reynolds', 'bethpearson@horton.com', '694.269.4169x6239');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('John', 'Phillips', 'xcabrera@gmail.com', '0958586779');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Robert', 'Orozco', 'alexandria84@gmail.com', '358-969-5360');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Jason', 'Watkins', 'gregory36@gmail.com', '001-901-200-6630');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Mark', 'Ochoa', 'ohickman@anderson-rowland.org', '(461)982-6931x123');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Scott', 'Lopez', 'walterbryant@vasquez-simpson.com', '5820528738');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Monica', 'Taylor', 'joy21@yahoo.com', '(861)348-2724x853');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Kevin', 'Garcia', 'williamsalex@yahoo.com', '001-630-192-7583');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Wesley', 'Jackson', 'dawsonelizabeth@hotmail.com', '497-225-4044x001');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Brittney', 'Brown', 'collinsjose@harris.biz', '669.306.3031x65417');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Marcia', 'Carpenter', 'mitchellgabrielle@gmail.com', '+1-811-864-1140');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Earl', 'Romero', 'patricia42@ramos.com', '016.540.7425');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Christy', 'Gibson', 'melissa58@smith.com', '239-362-3120x3965');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Gregory', 'Guzman', 'jessicasmith@hotmail.com', '001-403-558-9540');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Andrea', 'Parker', 'rodgerscaroline@hotmail.com', '001-652-069-0148x9789');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Kimberly', 'Stevens', 'gary40@yahoo.com', '263.559.8210');
INSERT INTO customer (first_name, last_name, email, phone_number) VALUES ('Christopher', 'Perez', 'brandi58@yahoo.com', '(118)882-6367');
INSERT INTO country (country_name) VALUES ('Kenya');
INSERT INTO country (country_name) VALUES ('USA');
INSERT INTO country (country_name) VALUES ('UK');
INSERT INTO country (country_name) VALUES ('Germany');
INSERT INTO country (country_name) VALUES ('France');
INSERT INTO address (street, city, postal_code, country_id) VALUES ('15953 Nancy Extension Apt. 273', 'West Diane', '18851', 3);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('752 Lawson Prairie Suite 766', 'Lloydberg', '15051', 1);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('900 Robert Tunnel Apt. 097', 'Youngville', '06669', 2);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('44340 Christina Island Apt. 245', 'West Tasha', '80798', 2);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('49716 William Ranch', 'West Raymond', '87944', 4);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('3531 Anderson Locks Suite 746', 'Port Julieport', '22575', 1);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('0208 Beverly Neck Suite 868', 'Dunnstad', '98294', 3);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('84354 Jacobs Underpass Suite 053', 'Lake Coryview', '16922', 4);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('6754 Tracy Circle', 'Jessicaport', '68022', 5);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('919 Benjamin Pine', 'Mckinneyborough', '82228', 2);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('5995 Thomas Glen Apt. 925', 'Nelsonburgh', '31302', 4);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('4874 Andrea View', 'Jenniferland', '94993', 5);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('527 Gordon Centers', 'Michelleberg', '44798', 2);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('7258 Harris Mountains', 'East Adam', '97378', 3);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('084 Jennifer Key Suite 202', 'Sheenaland', '61970', 2);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('97073 Miguel Island', 'East Malloryburgh', '23482', 2);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('9318 Hopkins Harbor Apt. 042', 'Port Amanda', '20625', 4);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('412 Carter Bridge Apt. 887', 'North Colleen', '75194', 5);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('78423 Jessica Path Suite 688', 'Jamesmouth', '24936', 1);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('89913 Fritz Alley', 'North Angela', '70130', 3);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('452 Martinez Divide', 'East Brandishire', '38293', 2);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('328 Barnes Coves', 'Gloverside', '32005', 5);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('28543 Ponce Lock Apt. 680', 'North Amyfort', '42662', 1);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('7024 Carlson Underpass Apt. 462', 'Crawfordfurt', '92715', 5);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('48261 Randy Junction', 'North Emmachester', '93702', 5);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('067 Richard Drive', 'Debraport', '04803', 4);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('28768 Jackson Radial', 'Lake Christinaland', '27088', 2);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('13364 Jeffery Mill', 'Veronicafort', '68438', 4);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('4216 Lisa Plaza Suite 640', 'Cardenasberg', '60476', 4);
INSERT INTO address (street, city, postal_code, country_id) VALUES ('042 Bowers Prairie', 'Mariahland', '76879', 4);
INSERT INTO address_status (status_name) VALUES ('Active');
INSERT INTO address_status (status_name) VALUES ('Previous');
INSERT INTO address_status (status_name) VALUES ('Billing');
INSERT INTO address_status (status_name) VALUES ('Shipping');
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (5, 4, 2);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (5, 12, 2);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (8, 25, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (3, 10, 1);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (13, 10, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (1, 25, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (2, 27, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (2, 23, 2);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (12, 24, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (16, 5, 1);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (9, 24, 1);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (10, 28, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (9, 3, 4);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (19, 27, 2);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (2, 26, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (10, 22, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (14, 20, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (17, 8, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (5, 26, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (9, 18, 2);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (6, 26, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (3, 15, 4);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (20, 4, 4);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (12, 28, 1);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (7, 23, 4);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (1, 13, 2);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (16, 9, 3);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (5, 11, 2);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (18, 7, 4);
INSERT INTO customer_address (customer_id, address_id, status_id) VALUES (18, 27, 3);
INSERT INTO shipping_method (method_name, cost) VALUES ('Standard', 11.66);
INSERT INTO shipping_method (method_name, cost) VALUES ('Express', 13.76);
INSERT INTO shipping_method (method_name, cost) VALUES ('Overnight', 8.38);
INSERT INTO order_status (status_name) VALUES ('Pending');
INSERT INTO order_status (status_name) VALUES ('Shipped');
INSERT INTO order_status (status_name) VALUES ('Delivered');
INSERT INTO order_status (status_name) VALUES ('Cancelled');
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (11, 2, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (17, 1, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (6, 1, 2);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (8, 1, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (19, 2, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (4, 1, 2);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (3, 2, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (16, 2, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (5, 1, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (3, 1, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (15, 3, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (6, 1, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (11, 1, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (17, 1, 2);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (8, 2, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (7, 2, 2);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (5, 1, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (6, 2, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (3, 1, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (17, 1, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (3, 3, 2);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (18, 3, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (12, 2, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (20, 2, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (3, 2, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (12, 1, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (14, 1, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (8, 2, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (1, 2, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (1, 1, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (8, 1, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (15, 2, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (18, 2, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (12, 1, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (12, 1, 2);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (11, 1, 1);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (19, 1, 4);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (4, 2, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (4, 2, 3);
INSERT INTO cust_order (customer_id, shipping_method_id, status_id) VALUES (11, 1, 2);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (15, 27, 1, 91.76);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (40, 14, 5, 32.78);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (14, 23, 4, 96.98);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (4, 20, 2, 28.03);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (40, 9, 3, 99.12);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (25, 29, 5, 64.73);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (18, 13, 2, 41.14);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (26, 22, 5, 18.85);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (20, 9, 2, 49.63);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (28, 27, 3, 61.72);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (20, 20, 3, 54.06);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (36, 17, 1, 35.12);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (17, 26, 4, 65.59);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (18, 25, 3, 73.19);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (15, 21, 4, 60.09);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (26, 16, 1, 19.20);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (15, 4, 4, 37.61);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (19, 24, 5, 88.20);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (17, 24, 3, 71.93);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (2, 18, 2, 59.91);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (22, 4, 2, 62.56);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (35, 13, 4, 85.87);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (24, 26, 1, 69.59);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (38, 27, 5, 96.01);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (10, 30, 3, 30.19);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (7, 17, 3, 39.48);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (2, 28, 1, 83.50);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (39, 1, 2, 99.30);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (18, 16, 5, 53.73);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (13, 13, 3, 24.28);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (34, 19, 3, 26.33);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (23, 2, 2, 49.50);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (26, 5, 1, 74.45);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (16, 7, 5, 13.27);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (29, 30, 3, 42.25);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (36, 23, 3, 64.58);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (8, 28, 4, 16.41);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (8, 19, 1, 33.61);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (24, 19, 2, 77.33);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (13, 8, 5, 10.51);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (28, 27, 1, 81.87);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (8, 21, 1, 40.67);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (10, 23, 5, 37.68);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (19, 27, 1, 39.19);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (14, 24, 3, 80.82);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (13, 18, 3, 63.17);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (12, 6, 4, 92.73);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (35, 15, 1, 86.66);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (12, 4, 1, 75.50);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (21, 24, 5, 35.30);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (5, 6, 4, 45.90);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (12, 19, 1, 66.35);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (38, 13, 3, 98.40);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (22, 11, 5, 64.89);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (30, 29, 2, 61.11);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (10, 10, 4, 23.93);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (14, 6, 5, 69.02);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (22, 2, 5, 34.84);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (26, 25, 3, 83.31);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (12, 25, 5, 63.76);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (18, 29, 3, 45.73);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (31, 3, 5, 72.00);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (18, 5, 2, 14.86);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (36, 10, 3, 78.30);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (18, 17, 4, 44.25);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (12, 26, 2, 56.77);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (8, 5, 4, 22.90);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (19, 29, 3, 23.37);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (11, 26, 5, 97.44);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (36, 5, 2, 96.79);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (15, 3, 3, 21.42);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (30, 29, 3, 60.06);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (1, 7, 1, 11.29);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (23, 3, 3, 11.25);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (34, 22, 4, 64.30);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (2, 5, 2, 94.41);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (39, 12, 5, 98.65);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (8, 10, 4, 51.36);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (7, 24, 5, 39.79);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (35, 7, 2, 22.77);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (10, 16, 4, 83.45);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (14, 17, 3, 95.24);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (20, 5, 5, 18.03);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (40, 15, 1, 69.01);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (12, 2, 5, 41.22);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (35, 7, 1, 59.06);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (19, 18, 4, 61.99);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (24, 22, 1, 75.97);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (22, 26, 3, 85.03);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (22, 26, 4, 41.21);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (12, 17, 4, 22.35);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (13, 27, 4, 30.74);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (38, 6, 3, 91.99);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (12, 26, 5, 33.30);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (5, 9, 2, 34.31);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (25, 8, 3, 65.46);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (3, 15, 4, 40.91);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (33, 10, 3, 48.29);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (27, 20, 1, 85.50);
INSERT INTO order_line (order_id, book_id, quantity, price) VALUES (34, 6, 4, 90.78);
INSERT INTO order_history (order_id, status_id) VALUES (13, 1);
INSERT INTO order_history (order_id, status_id) VALUES (3, 2);
INSERT INTO order_history (order_id, status_id) VALUES (29, 3);
INSERT INTO order_history (order_id, status_id) VALUES (25, 4);
INSERT INTO order_history (order_id, status_id) VALUES (13, 1);
INSERT INTO order_history (order_id, status_id) VALUES (20, 1);
INSERT INTO order_history (order_id, status_id) VALUES (38, 4);
INSERT INTO order_history (order_id, status_id) VALUES (19, 2);
INSERT INTO order_history (order_id, status_id) VALUES (14, 4);
INSERT INTO order_history (order_id, status_id) VALUES (16, 4);
INSERT INTO order_history (order_id, status_id) VALUES (2, 3);
INSERT INTO order_history (order_id, status_id) VALUES (24, 2);
INSERT INTO order_history (order_id, status_id) VALUES (21, 3);
INSERT INTO order_history (order_id, status_id) VALUES (7, 2);
INSERT INTO order_history (order_id, status_id) VALUES (6, 2);
INSERT INTO order_history (order_id, status_id) VALUES (4, 3);
INSERT INTO order_history (order_id, status_id) VALUES (28, 4);
INSERT INTO order_history (order_id, status_id) VALUES (9, 4);
INSERT INTO order_history (order_id, status_id) VALUES (2, 1);
INSERT INTO order_history (order_id, status_id) VALUES (21, 2);
INSERT INTO order_history (order_id, status_id) VALUES (12, 2);
INSERT INTO order_history (order_id, status_id) VALUES (37, 4);
INSERT INTO order_history (order_id, status_id) VALUES (30, 3);
INSERT INTO order_history (order_id, status_id) VALUES (20, 1);
INSERT INTO order_history (order_id, status_id) VALUES (1, 2);
INSERT INTO order_history (order_id, status_id) VALUES (27, 2);
INSERT INTO order_history (order_id, status_id) VALUES (6, 3);
INSERT INTO order_history (order_id, status_id) VALUES (6, 3);
INSERT INTO order_history (order_id, status_id) VALUES (9, 2);
INSERT INTO order_history (order_id, status_id) VALUES (29, 3);
INSERT INTO order_history (order_id, status_id) VALUES (12, 4);
INSERT INTO order_history (order_id, status_id) VALUES (27, 4);
INSERT INTO order_history (order_id, status_id) VALUES (33, 3);
INSERT INTO order_history (order_id, status_id) VALUES (12, 2);
INSERT INTO order_history (order_id, status_id) VALUES (38, 1);
INSERT INTO order_history (order_id, status_id) VALUES (37, 3);
INSERT INTO order_history (order_id, status_id) VALUES (32, 1);
INSERT INTO order_history (order_id, status_id) VALUES (40, 4);
INSERT INTO order_history (order_id, status_id) VALUES (31, 2);
INSERT INTO order_history (order_id, status_id) VALUES (12, 2);
INSERT INTO order_history (order_id, status_id) VALUES (1, 1);
INSERT INTO order_history (order_id, status_id) VALUES (3, 3);
INSERT INTO order_history (order_id, status_id) VALUES (3, 3);
INSERT INTO order_history (order_id, status_id) VALUES (31, 1);
INSERT INTO order_history (order_id, status_id) VALUES (34, 1);
INSERT INTO order_history (order_id, status_id) VALUES (23, 3);
INSERT INTO order_history (order_id, status_id) VALUES (11, 3);
INSERT INTO order_history (order_id, status_id) VALUES (29, 1);
INSERT INTO order_history (order_id, status_id) VALUES (18, 1);
INSERT INTO order_history (order_id, status_id) VALUES (25, 4);
INSERT INTO order_history (order_id, status_id) VALUES (35, 3);
INSERT INTO order_history (order_id, status_id) VALUES (3, 3);
INSERT INTO order_history (order_id, status_id) VALUES (13, 4);
INSERT INTO order_history (order_id, status_id) VALUES (10, 2);
INSERT INTO order_history (order_id, status_id) VALUES (9, 2);
INSERT INTO order_history (order_id, status_id) VALUES (21, 3);
INSERT INTO order_history (order_id, status_id) VALUES (32, 1);
INSERT INTO order_history (order_id, status_id) VALUES (13, 3);
INSERT INTO order_history (order_id, status_id) VALUES (1, 3);
INSERT INTO order_history (order_id, status_id) VALUES (6, 1);

